New command !mdocstring
ManimCommunity/DiscordManimator pull request #15
Opened 2021-05-19 12:07 UTC by naveen521kk

2021-05-19 12:26 UTC, infiniteregrets commented
Can you explain a bit more about the !mdocstring command and possibly share a screenshot of what the end result looks like

2021-05-19 12:39 UTC, kolibril13 commented
This incorporates https://github.com/ManimCommunity/DiscordManimator/issues/14 (@infiniteregrets : you can find a screenshot there).
Thanks a lot, naveen, for this pull request!

2021-05-19 12:48 UTC, naveen521kk commented
@infiniteregrets something like 
![](https://media.discordapp.net/attachments/581738732646957057/844541380273635419/unknown.png?width=718&height=450)

2021-05-19 13:04 UTC, infiniteregrets commented
Oh, I think this can be helpful for you guys! And this can be merged after #11, except you will have to make a few changes to your code. Great work!

2021-05-19 13:15 UTC, naveen521kk commented
I think this can be merged first rather than that one. Since https://github.com/ManimCommunity/DiscordManimator/pull/11 does major changes on the whole structure it would easy to make changes there and fix conflicts rather than changing this here.

2021-05-19 20:10 UTC, kolibril13 commented
I don't mind in which order we merge these prs.
But it would be nice if this could be merged soon, as we have an event soon, where this docs feature could be really helpful!

2021-05-20 05:37 UTC, Darylgolden requested changes
Minor typo, otherwise LGTM

2021-05-20 05:37 UTC, Darylgolden commented on DiscordManimator.py
> +                    "content": "Can't find a unique Class Name. Either pass it as an argument or use standart methods."
```suggestion
                    "content": "Can't find a unique Class Name. Either pass it as an argument or use standard methods."
```

2021-05-20 10:45 UTC, naveen521kk commented
@kolibril13 does this look good to you?

Also, @behackl I have added poetry configurations, so while deploying you can either use a venv from poetry or run `poetry export -o requirements.txt` and run `pip install -r requirements.txt` while deploying.

2021-05-20 11:52 UTC, kolibril13 commented
> @kolibril13 does this look good to you?
> 
> Also, @behackl I have added poetry configurations, so while deploying you can either use a venv from poetry or run `poetry export -o requirements.txt` and run `pip install -r requirements.txt` while deploying.

yes, it looks good to me!
Thanks a lot again for the efforts you are doing here, this is a huge step to make it easier to contribute examples to the docs! :)

2021-05-20 11:52 UTC, kolibril13 approved these changes

2021-05-20 11:53 UTC, naveen521kk commented
Ok merging :rocket:

2021-05-20 11:53 UTC, merged

2021-05-20 11:58 UTC, behackl commented
Two remarks:

- Given that there is no automatic deployment setup for this, I'd appreciate if you'd let me merge -- otherwise it might happen that updates won't be deployed. (I don't really mind, it's just easier to miss stuff on my end.)
- In general, I like the idea of having a command that helps formatting docstrings -- but honestly, I think the actual work of composing the docstring should be made by Manim, potentially in a `manim docs` subcommand (which we should look into anyways, to make it easier to render single documentation pages).

The changes here are fine obviously, no need to revert anything. I'd still prefer PRing the formatting utility to the library itself. Only having it in our bot seems weird to me.

2021-05-20 12:04 UTC, kolibril13 commented
Do we have to restart the bot to apply the changes?

2021-05-20 12:06 UTC, naveen521kk commented
> I'd appreciate if you'd let me merge 

:+1:. Maybe if it is possible we can set up something like automatic deployment using GHA.

> In general, I like the idea of having a command that helps formatting docstrings -- but honestly, I think the actual work of composing the docstring should be made by Manim, potentially in a manim docs subcommand (which we should look into anyways, to make it easier to render single documentation pages).

I am wondering how it would be helpful for a general user. I think it should be somewhere in the `scripts` folder in manim but shouldn't be build into Manim itself. Also, rendering single documentation separately seems like a nice and useful idea.